---
- hosts: all
  gather_facts: no

  tasks:
  - name: check for port 80
    wait_for:
      port: 80
      timeout: 5
    ignore_errors: yes
    register: check_web

  - debug:
      msg: “Port 80 is not open and listening”
    when: check_web.failed

