---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed

  - name: stop httpd
    service:
      name: httpd
      state: stopped
